version: '3.7'

services:
  #spring:
  #  image: springio/gs-spring-boot-docker
  #  networks:
  #    - grafana_network
  #  ports:
  #    - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.38.0
    networks:
      - grafana_network
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.1.4
    user: "$UID:$GID"
    networks:
      - grafana_network
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

networks:
  grafana_network: