version: '3.7'

services:
  spring:
    image: rhdesouza/observability-api:0.0.1-SNAPSHOT
    container_name: api-observability
    networks:
      - observability_network
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/
    environment:
      - datasource.url=mysql://mysql/observability?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo
    depends_on:
      - mysql

  mysql:
    container_name: mysql_observability
    image: mysql:latest
    networks:
      - observability_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "observability"
    ports:
      - 3306:3306
    restart: always

  prometheus:
    image: prom/prometheus:v2.38.0
    networks:
      - observability_network
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    networks:
      - observability_network
    container_name: grafana-container
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:465
      - GF_SMTP_USER=rhdesouza@gmail.com
      - GF_SMTP_PASSWORD=Rafael@1985
      - GF_SMTP_SKIP_VERIFY=true

  loki:
    image: grafana/loki:2.0.0
    container_name: loki-service
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
      #- "-print-config.stderr=true"
    networks:
      - observability_network

  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail-service
    command: -config.file=./etc/promtail/config.yaml
    volumes:
      - ./logs/:/var/log/
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - ./tmp:/tmp
    ports:
      - "9080:9080"
    depends_on:
      - loki
    networks:
      - observability_network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-service
    ports:
      - 9411:9411
    networks:
      - observability_network
    restart: always

  k6:
    image: loadimpact/k6:latest
    container_name: k6-service
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
    networks:
      - observability_network

networks:
  observability_network:
