version: '3.7'

services:
  spring:
    image: springio/gs-spring-boot-docker
    container_name: api-obervability
    networks:
      - grafana_network
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
      - datasource.url=mysql://mysql/observability?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo
    depends_on:
      - mysql

  mysql:
    container_name: mysql_observability
    image: mysql:latest
    networks:
      - grafana_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "observability"
    ports:
      - 3306:3306

  prometheus:
    image: prom/prometheus:v2.38.0
    networks:
      - grafana_network
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    networks:
      - grafana_network
    container_name: grafana-container
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

  loki:
    image: grafana/loki:2.2.1
    container_name: loki-service
    volumes:
      - ./loki/:/etc/loki/
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - grafana_network

  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail-service
    volumes:
      - ./logs/:/var/log/
      - ./promtail/:/etc/promtail/
    command: '--config.file=/etc/promtail/promtail.yaml'
    networks:
      - grafana_network

networks:
  grafana_network:
