version: '3.7'

services:
  #spring:
  #  image: springio/gs-spring-boot-docker
  #  networks:
  #    - grafana_network
  #  ports:
  #    - "8080:8080"

  mysql:
    container_name: mysql_observability
    image: mysql:latest
    networks:
      - grafana_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "observability"
    ports:
      - 3306:3306

  prometheus:
    image: prom/prometheus:v2.38.0
    networks:
      - grafana_network
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    networks:
      - grafana_network
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

  loki:
    image: grafana/loki:2.2.1
    container_name: loki-service
    volumes:
      #    将loki的配置文件挂载到本地 c:/docker/loki 目录
      - ./loki/:/etc/loki/
    ports:
      - "3100:3100"
    command: '--config.file=/etc/loki/loki.yml'
    networks:
      - grafana_network

  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail-service
    volumes:
      #  为了读取本地的日志目录，这个是个默认配置目的就是为跑起来，生产肯定不是这样的。
      #- c:/docker/log:/var/log/
      - /promtail/:/var/log/
      #  promtail  的配置文件也挂载到本地 c:/docker/promtail目录
      #- c:/docker/promtail:/etc/promtail/
      - ./promtail/:/etc/promtail/
    command: '--config.file=/etc/promtail/promtail.yml'
    networks:
      - grafana_network

networks:
  grafana_network: