spring:
  application:
    name: observability-api
  datasource:
    #diver-class-name: com.mysql.cj.jdbc.Driver
    diver-class-name: io.opentracing.contrib.jdbc.TracingDriver
    url: jdbc:${datasource.url:mysql://localhost/observability?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo}
    username: root
    password: root
    sqlScriptEncoding: UTF-8

logging:
  file:
    path: ./scripts/monitoring/logs/

api:
  security:
    user: admin
    password: admin

flyway:
  url: jdbc:${datasource.url:mysql://localhost/observability?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo}
  schemas: observability
  user: root
  password: root
  createSchemas: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      #base-path: /actuator
      exposure:
        include: [ "health", "metrics","prometheus" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: 8080

spring-doc:
  swagger-ui:
    path: /swagger-ui.html
